display_name: KitonyBox

icon: ./assets/images/icon.png

keywords:
  - KitonyBox
  - Clash
  - ClashMeta
  - Proxy

generic_name: KitonyBox

categories:
  - Network

startup_notify: true
startup_wm_class: com.appshub.kitonybox

include: []